# Generated by Django 2.2 on 2019-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
