# Generated by Django 2.2 on 2019-07-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20190714_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
